# On every push this script is executed
# https://www.getzola.org/documentation/deployment/github-pages/
on: push
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0
      - name: build_and_deploy
        uses: lewiszlw/zola-deploy-action@master
        env:
          BUILD_THEMES: false
          # Target branch
          PAGES_BRANCH: gh-pages
          # Provide personal access token
          TOKEN: ${{ secrets.ZOLA_TOKEN }}
          # Or if publishing to the same repo, use the automatic token
          #TOKEN: ${{ secrets.GITHUB_TOKEN }}